# Generated by Django 5.1.4 on 2025-03-19 21:02

from django.db import migrations

def populate_status(apps, schemaeditor):
    statuses = {
        "published":"A post that is visible to all on thesite",
        "draft":"A post that only the author can see and interact with",
        "archived":"A post that is only visible to all logged users.",
    }
    status = apps.get_model("posts","status")
    for key, value in statuses.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
    ]
